const fs = require('fs');
const path = require('path');

const pagesDir = '/opt/drimports/drimports-frontend/src/pages';
const files = ['Products.tsx', 'Sales.tsx', 'Imports.tsx', 'Trips.tsx', 'Clients.tsx', 'Users.tsx', 'Brands.tsx', 'Categories.tsx'];

files.forEach(file => {
  const filePath = path.join(pagesDir, file);
  if (!fs.existsSync(filePath)) return;

  let content = fs.readFileSync(filePath, 'utf8');

  // 1. Change ITEMS_PER_PAGE to 11
  content = content.replace(/ITEMS_PER_PAGE = \d+;/, 'ITEMS_PER_PAGE = 11;');

  // 2. Ensure table rows have a fixed height
  content = content.replace(/<tr key=\{([^\}]+)\} className="([^"]+)"/g, (match, key, classes) => {
    if (!classes.includes('h-[60px]')) {
      return `<tr key={${key}} className="${classes} h-[60px]"`;
    }
    return match;
  });

  // 3. Ensure the pagination footer is ALWAYS rendered and has a fixed height
  // Currently looks like:
  // {totalPages > 1 && (
  //   <div className="p-3 px-4 bg-slate-50/50 border-t border-slate-100 flex items-center justify-between flex-none text-xs text-slate-500">
  //     ...
  //   </div>
  // )}
  // We need to change it to always render.
  
  const paginationRegex = /\{totalPages > 1 && \(\s*(<div className="p-3 px-4 bg-slate-50\/50 border-t border-slate-100 flex items-center justify-between flex-none text-xs text-slate-500[\s\S]*?)<\div>\s*\)\}/;
  
  if (paginationRegex.test(content)) {
    // Some files might have different structures inside, but generally:
    content = content.replace(paginationRegex, (match, divContent) => {
      // Replace the inner parts to handle 0 items
      let newDiv = divContent.replace(/<div className="p-3 px-4 bg-slate-50\/50 border-t border-slate-100 flex items-center justify-between flex-none text-xs text-slate-500"/, 
        `<div className="p-3 px-4 bg-slate-50/50 border-t border-slate-100 flex items-center justify-between flex-none text-xs text-slate-500 min-h-[52px]"`);
        
      return `{totalPages > 0 ? (
            ${newDiv}
            </div>
          ) : (
            <div className="p-3 px-4 bg-slate-50/50 border-t border-slate-100 flex items-center justify-between flex-none text-xs text-slate-500 min-h-[52px]">
              <span>Nenhum registro encontrado</span>
            </div>
          )}`;
    });
  }

  // Same for pagination with totalPages > 0, just in case it's already modified
  // Wait, if it doesn't match exactly, we should just find the pagination block.
  // The structure is very uniform because they were copy-pasted or generated by the same LLM.
  
  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`Processed ${file}`);
});
